/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConvitesRouteImport } from './routes/convites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeladaIdRouteImport } from './routes/pelada.$id'
import { Route as PeladaIdUsuariosRouteImport } from './routes/pelada.$id_.usuarios'
import { Route as PeladaIdListaRouteImport } from './routes/pelada.$id_.lista'
import { Route as PeladaIdHistoricoRouteImport } from './routes/pelada.$id_.historico'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvitesRoute = ConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdRoute = PeladaIdRouteImport.update({
  id: '/pelada/$id',
  path: '/pelada/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdUsuariosRoute = PeladaIdUsuariosRouteImport.update({
  id: '/pelada/$id_/usuarios',
  path: '/pelada/$id/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdListaRoute = PeladaIdListaRouteImport.update({
  id: '/pelada/$id_/lista',
  path: '/pelada/$id/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdHistoricoRoute = PeladaIdHistoricoRouteImport.update({
  id: '/pelada/$id_/historico',
  path: '/pelada/$id/historico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convites': typeof ConvitesRoute
  '/dashboard': typeof DashboardRoute
  '/pelada/$id': typeof PeladaIdRoute
  '/pelada/$id/historico': typeof PeladaIdHistoricoRoute
  '/pelada/$id/lista': typeof PeladaIdListaRoute
  '/pelada/$id/usuarios': typeof PeladaIdUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convites': typeof ConvitesRoute
  '/dashboard': typeof DashboardRoute
  '/pelada/$id': typeof PeladaIdRoute
  '/pelada/$id/historico': typeof PeladaIdHistoricoRoute
  '/pelada/$id/lista': typeof PeladaIdListaRoute
  '/pelada/$id/usuarios': typeof PeladaIdUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convites': typeof ConvitesRoute
  '/dashboard': typeof DashboardRoute
  '/pelada/$id': typeof PeladaIdRoute
  '/pelada/$id_/historico': typeof PeladaIdHistoricoRoute
  '/pelada/$id_/lista': typeof PeladaIdListaRoute
  '/pelada/$id_/usuarios': typeof PeladaIdUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convites'
    | '/dashboard'
    | '/pelada/$id'
    | '/pelada/$id/historico'
    | '/pelada/$id/lista'
    | '/pelada/$id/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convites'
    | '/dashboard'
    | '/pelada/$id'
    | '/pelada/$id/historico'
    | '/pelada/$id/lista'
    | '/pelada/$id/usuarios'
  id:
    | '__root__'
    | '/'
    | '/convites'
    | '/dashboard'
    | '/pelada/$id'
    | '/pelada/$id_/historico'
    | '/pelada/$id_/lista'
    | '/pelada/$id_/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvitesRoute: typeof ConvitesRoute
  DashboardRoute: typeof DashboardRoute
  PeladaIdRoute: typeof PeladaIdRoute
  PeladaIdHistoricoRoute: typeof PeladaIdHistoricoRoute
  PeladaIdListaRoute: typeof PeladaIdListaRoute
  PeladaIdUsuariosRoute: typeof PeladaIdUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convites': {
      id: '/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof ConvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id': {
      id: '/pelada/$id'
      path: '/pelada/$id'
      fullPath: '/pelada/$id'
      preLoaderRoute: typeof PeladaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/usuarios': {
      id: '/pelada/$id_/usuarios'
      path: '/pelada/$id/usuarios'
      fullPath: '/pelada/$id/usuarios'
      preLoaderRoute: typeof PeladaIdUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/lista': {
      id: '/pelada/$id_/lista'
      path: '/pelada/$id/lista'
      fullPath: '/pelada/$id/lista'
      preLoaderRoute: typeof PeladaIdListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/historico': {
      id: '/pelada/$id_/historico'
      path: '/pelada/$id/historico'
      fullPath: '/pelada/$id/historico'
      preLoaderRoute: typeof PeladaIdHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvitesRoute: ConvitesRoute,
  DashboardRoute: DashboardRoute,
  PeladaIdRoute: PeladaIdRoute,
  PeladaIdHistoricoRoute: PeladaIdHistoricoRoute,
  PeladaIdListaRoute: PeladaIdListaRoute,
  PeladaIdUsuariosRoute: PeladaIdUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
