/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConvitesRouteImport } from './routes/convites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeladaIdRouteImport } from './routes/pelada.$id'
import { Route as FutevoleiOnboardingRouteImport } from './routes/futevolei.onboarding'
import { Route as FutevoleiInstrutorRouteImport } from './routes/futevolei.instrutor'
import { Route as PeladaIdUsuariosRouteImport } from './routes/pelada.$id_.usuarios'
import { Route as PeladaIdRankingsRouteImport } from './routes/pelada.$id_.rankings'
import { Route as PeladaIdPerfilRouteImport } from './routes/pelada.$id_.perfil'
import { Route as PeladaIdPartidaRouteImport } from './routes/pelada.$id_.partida'
import { Route as PeladaIdListaRouteImport } from './routes/pelada.$id_.lista'
import { Route as PeladaIdHistoricoRouteImport } from './routes/pelada.$id_.historico'
import { Route as PeladaIdCampeonatoRouteImport } from './routes/pelada.$id_.campeonato'
import { Route as PeladaIdAdminRouteImport } from './routes/pelada.$id_.admin'
import { Route as FutevoleiInstrutorCadastroRouteImport } from './routes/futevolei.instrutor.cadastro'
import { Route as FutevoleiAlunoCadastroRouteImport } from './routes/futevolei.aluno.cadastro'
import { Route as PeladaIdJogadorUserIdRouteImport } from './routes/pelada.$id_.jogador.$userId'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvitesRoute = ConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdRoute = PeladaIdRouteImport.update({
  id: '/pelada/$id',
  path: '/pelada/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FutevoleiOnboardingRoute = FutevoleiOnboardingRouteImport.update({
  id: '/futevolei/onboarding',
  path: '/futevolei/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FutevoleiInstrutorRoute = FutevoleiInstrutorRouteImport.update({
  id: '/futevolei/instrutor',
  path: '/futevolei/instrutor',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdUsuariosRoute = PeladaIdUsuariosRouteImport.update({
  id: '/pelada/$id_/usuarios',
  path: '/pelada/$id/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdRankingsRoute = PeladaIdRankingsRouteImport.update({
  id: '/pelada/$id_/rankings',
  path: '/pelada/$id/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdPerfilRoute = PeladaIdPerfilRouteImport.update({
  id: '/pelada/$id_/perfil',
  path: '/pelada/$id/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdPartidaRoute = PeladaIdPartidaRouteImport.update({
  id: '/pelada/$id_/partida',
  path: '/pelada/$id/partida',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdListaRoute = PeladaIdListaRouteImport.update({
  id: '/pelada/$id_/lista',
  path: '/pelada/$id/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdHistoricoRoute = PeladaIdHistoricoRouteImport.update({
  id: '/pelada/$id_/historico',
  path: '/pelada/$id/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdCampeonatoRoute = PeladaIdCampeonatoRouteImport.update({
  id: '/pelada/$id_/campeonato',
  path: '/pelada/$id/campeonato',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdAdminRoute = PeladaIdAdminRouteImport.update({
  id: '/pelada/$id_/admin',
  path: '/pelada/$id/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FutevoleiInstrutorCadastroRoute =
  FutevoleiInstrutorCadastroRouteImport.update({
    id: '/cadastro',
    path: '/cadastro',
    getParentRoute: () => FutevoleiInstrutorRoute,
  } as any)
const FutevoleiAlunoCadastroRoute = FutevoleiAlunoCadastroRouteImport.update({
  id: '/futevolei/aluno/cadastro',
  path: '/futevolei/aluno/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdJogadorUserIdRoute = PeladaIdJogadorUserIdRouteImport.update({
  id: '/pelada/$id_/jogador/$userId',
  path: '/pelada/$id/jogador/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convites': typeof ConvitesRoute
  '/dashboard': typeof DashboardRoute
  '/super-admin': typeof SuperAdminRoute
  '/futevolei/instrutor': typeof FutevoleiInstrutorRouteWithChildren
  '/futevolei/onboarding': typeof FutevoleiOnboardingRoute
  '/pelada/$id': typeof PeladaIdRoute
  '/futevolei/aluno/cadastro': typeof FutevoleiAlunoCadastroRoute
  '/futevolei/instrutor/cadastro': typeof FutevoleiInstrutorCadastroRoute
  '/pelada/$id/admin': typeof PeladaIdAdminRoute
  '/pelada/$id/campeonato': typeof PeladaIdCampeonatoRoute
  '/pelada/$id/historico': typeof PeladaIdHistoricoRoute
  '/pelada/$id/lista': typeof PeladaIdListaRoute
  '/pelada/$id/partida': typeof PeladaIdPartidaRoute
  '/pelada/$id/perfil': typeof PeladaIdPerfilRoute
  '/pelada/$id/rankings': typeof PeladaIdRankingsRoute
  '/pelada/$id/usuarios': typeof PeladaIdUsuariosRoute
  '/pelada/$id/jogador/$userId': typeof PeladaIdJogadorUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convites': typeof ConvitesRoute
  '/dashboard': typeof DashboardRoute
  '/super-admin': typeof SuperAdminRoute
  '/futevolei/instrutor': typeof FutevoleiInstrutorRouteWithChildren
  '/futevolei/onboarding': typeof FutevoleiOnboardingRoute
  '/pelada/$id': typeof PeladaIdRoute
  '/futevolei/aluno/cadastro': typeof FutevoleiAlunoCadastroRoute
  '/futevolei/instrutor/cadastro': typeof FutevoleiInstrutorCadastroRoute
  '/pelada/$id/admin': typeof PeladaIdAdminRoute
  '/pelada/$id/campeonato': typeof PeladaIdCampeonatoRoute
  '/pelada/$id/historico': typeof PeladaIdHistoricoRoute
  '/pelada/$id/lista': typeof PeladaIdListaRoute
  '/pelada/$id/partida': typeof PeladaIdPartidaRoute
  '/pelada/$id/perfil': typeof PeladaIdPerfilRoute
  '/pelada/$id/rankings': typeof PeladaIdRankingsRoute
  '/pelada/$id/usuarios': typeof PeladaIdUsuariosRoute
  '/pelada/$id/jogador/$userId': typeof PeladaIdJogadorUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convites': typeof ConvitesRoute
  '/dashboard': typeof DashboardRoute
  '/super-admin': typeof SuperAdminRoute
  '/futevolei/instrutor': typeof FutevoleiInstrutorRouteWithChildren
  '/futevolei/onboarding': typeof FutevoleiOnboardingRoute
  '/pelada/$id': typeof PeladaIdRoute
  '/futevolei/aluno/cadastro': typeof FutevoleiAlunoCadastroRoute
  '/futevolei/instrutor/cadastro': typeof FutevoleiInstrutorCadastroRoute
  '/pelada/$id_/admin': typeof PeladaIdAdminRoute
  '/pelada/$id_/campeonato': typeof PeladaIdCampeonatoRoute
  '/pelada/$id_/historico': typeof PeladaIdHistoricoRoute
  '/pelada/$id_/lista': typeof PeladaIdListaRoute
  '/pelada/$id_/partida': typeof PeladaIdPartidaRoute
  '/pelada/$id_/perfil': typeof PeladaIdPerfilRoute
  '/pelada/$id_/rankings': typeof PeladaIdRankingsRoute
  '/pelada/$id_/usuarios': typeof PeladaIdUsuariosRoute
  '/pelada/$id_/jogador/$userId': typeof PeladaIdJogadorUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convites'
    | '/dashboard'
    | '/super-admin'
    | '/futevolei/instrutor'
    | '/futevolei/onboarding'
    | '/pelada/$id'
    | '/futevolei/aluno/cadastro'
    | '/futevolei/instrutor/cadastro'
    | '/pelada/$id/admin'
    | '/pelada/$id/campeonato'
    | '/pelada/$id/historico'
    | '/pelada/$id/lista'
    | '/pelada/$id/partida'
    | '/pelada/$id/perfil'
    | '/pelada/$id/rankings'
    | '/pelada/$id/usuarios'
    | '/pelada/$id/jogador/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convites'
    | '/dashboard'
    | '/super-admin'
    | '/futevolei/instrutor'
    | '/futevolei/onboarding'
    | '/pelada/$id'
    | '/futevolei/aluno/cadastro'
    | '/futevolei/instrutor/cadastro'
    | '/pelada/$id/admin'
    | '/pelada/$id/campeonato'
    | '/pelada/$id/historico'
    | '/pelada/$id/lista'
    | '/pelada/$id/partida'
    | '/pelada/$id/perfil'
    | '/pelada/$id/rankings'
    | '/pelada/$id/usuarios'
    | '/pelada/$id/jogador/$userId'
  id:
    | '__root__'
    | '/'
    | '/convites'
    | '/dashboard'
    | '/super-admin'
    | '/futevolei/instrutor'
    | '/futevolei/onboarding'
    | '/pelada/$id'
    | '/futevolei/aluno/cadastro'
    | '/futevolei/instrutor/cadastro'
    | '/pelada/$id_/admin'
    | '/pelada/$id_/campeonato'
    | '/pelada/$id_/historico'
    | '/pelada/$id_/lista'
    | '/pelada/$id_/partida'
    | '/pelada/$id_/perfil'
    | '/pelada/$id_/rankings'
    | '/pelada/$id_/usuarios'
    | '/pelada/$id_/jogador/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvitesRoute: typeof ConvitesRoute
  DashboardRoute: typeof DashboardRoute
  SuperAdminRoute: typeof SuperAdminRoute
  FutevoleiInstrutorRoute: typeof FutevoleiInstrutorRouteWithChildren
  FutevoleiOnboardingRoute: typeof FutevoleiOnboardingRoute
  PeladaIdRoute: typeof PeladaIdRoute
  FutevoleiAlunoCadastroRoute: typeof FutevoleiAlunoCadastroRoute
  PeladaIdAdminRoute: typeof PeladaIdAdminRoute
  PeladaIdCampeonatoRoute: typeof PeladaIdCampeonatoRoute
  PeladaIdHistoricoRoute: typeof PeladaIdHistoricoRoute
  PeladaIdListaRoute: typeof PeladaIdListaRoute
  PeladaIdPartidaRoute: typeof PeladaIdPartidaRoute
  PeladaIdPerfilRoute: typeof PeladaIdPerfilRoute
  PeladaIdRankingsRoute: typeof PeladaIdRankingsRoute
  PeladaIdUsuariosRoute: typeof PeladaIdUsuariosRoute
  PeladaIdJogadorUserIdRoute: typeof PeladaIdJogadorUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convites': {
      id: '/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof ConvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id': {
      id: '/pelada/$id'
      path: '/pelada/$id'
      fullPath: '/pelada/$id'
      preLoaderRoute: typeof PeladaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futevolei/onboarding': {
      id: '/futevolei/onboarding'
      path: '/futevolei/onboarding'
      fullPath: '/futevolei/onboarding'
      preLoaderRoute: typeof FutevoleiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futevolei/instrutor': {
      id: '/futevolei/instrutor'
      path: '/futevolei/instrutor'
      fullPath: '/futevolei/instrutor'
      preLoaderRoute: typeof FutevoleiInstrutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/usuarios': {
      id: '/pelada/$id_/usuarios'
      path: '/pelada/$id/usuarios'
      fullPath: '/pelada/$id/usuarios'
      preLoaderRoute: typeof PeladaIdUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/rankings': {
      id: '/pelada/$id_/rankings'
      path: '/pelada/$id/rankings'
      fullPath: '/pelada/$id/rankings'
      preLoaderRoute: typeof PeladaIdRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/perfil': {
      id: '/pelada/$id_/perfil'
      path: '/pelada/$id/perfil'
      fullPath: '/pelada/$id/perfil'
      preLoaderRoute: typeof PeladaIdPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/partida': {
      id: '/pelada/$id_/partida'
      path: '/pelada/$id/partida'
      fullPath: '/pelada/$id/partida'
      preLoaderRoute: typeof PeladaIdPartidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/lista': {
      id: '/pelada/$id_/lista'
      path: '/pelada/$id/lista'
      fullPath: '/pelada/$id/lista'
      preLoaderRoute: typeof PeladaIdListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/historico': {
      id: '/pelada/$id_/historico'
      path: '/pelada/$id/historico'
      fullPath: '/pelada/$id/historico'
      preLoaderRoute: typeof PeladaIdHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/campeonato': {
      id: '/pelada/$id_/campeonato'
      path: '/pelada/$id/campeonato'
      fullPath: '/pelada/$id/campeonato'
      preLoaderRoute: typeof PeladaIdCampeonatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/admin': {
      id: '/pelada/$id_/admin'
      path: '/pelada/$id/admin'
      fullPath: '/pelada/$id/admin'
      preLoaderRoute: typeof PeladaIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futevolei/instrutor/cadastro': {
      id: '/futevolei/instrutor/cadastro'
      path: '/cadastro'
      fullPath: '/futevolei/instrutor/cadastro'
      preLoaderRoute: typeof FutevoleiInstrutorCadastroRouteImport
      parentRoute: typeof FutevoleiInstrutorRoute
    }
    '/futevolei/aluno/cadastro': {
      id: '/futevolei/aluno/cadastro'
      path: '/futevolei/aluno/cadastro'
      fullPath: '/futevolei/aluno/cadastro'
      preLoaderRoute: typeof FutevoleiAlunoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id_/jogador/$userId': {
      id: '/pelada/$id_/jogador/$userId'
      path: '/pelada/$id/jogador/$userId'
      fullPath: '/pelada/$id/jogador/$userId'
      preLoaderRoute: typeof PeladaIdJogadorUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FutevoleiInstrutorRouteChildren {
  FutevoleiInstrutorCadastroRoute: typeof FutevoleiInstrutorCadastroRoute
}

const FutevoleiInstrutorRouteChildren: FutevoleiInstrutorRouteChildren = {
  FutevoleiInstrutorCadastroRoute: FutevoleiInstrutorCadastroRoute,
}

const FutevoleiInstrutorRouteWithChildren =
  FutevoleiInstrutorRoute._addFileChildren(FutevoleiInstrutorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvitesRoute: ConvitesRoute,
  DashboardRoute: DashboardRoute,
  SuperAdminRoute: SuperAdminRoute,
  FutevoleiInstrutorRoute: FutevoleiInstrutorRouteWithChildren,
  FutevoleiOnboardingRoute: FutevoleiOnboardingRoute,
  PeladaIdRoute: PeladaIdRoute,
  FutevoleiAlunoCadastroRoute: FutevoleiAlunoCadastroRoute,
  PeladaIdAdminRoute: PeladaIdAdminRoute,
  PeladaIdCampeonatoRoute: PeladaIdCampeonatoRoute,
  PeladaIdHistoricoRoute: PeladaIdHistoricoRoute,
  PeladaIdListaRoute: PeladaIdListaRoute,
  PeladaIdPartidaRoute: PeladaIdPartidaRoute,
  PeladaIdPerfilRoute: PeladaIdPerfilRoute,
  PeladaIdRankingsRoute: PeladaIdRankingsRoute,
  PeladaIdUsuariosRoute: PeladaIdUsuariosRoute,
  PeladaIdJogadorUserIdRoute: PeladaIdJogadorUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
